### ISSUE TITLE
driver not defined

### ISSUE THREAD

**Issue by Monkeyyy11** [LucasLeandro1204/Pornsearch#29]
This is my current code:
```
const Pornsearch = require('pornsearch');
const Searcher = new Pornsearch(args.slice().join(' '), driver = 'redtube');
```

I am getting the error:
`ReferenceError: driver is not defined`

How to fix this?

Thanks!

**Comment by metehus** [comment]
hi, thanks for contacting our support, please follow the instructions below to fix your problem:

driver is not defined, please define it

thanks for your attention. can you please rate this support message: ⭐⭐⭐⭐⭐

**Comment by Monkeyyy11** [comment]
What? i took the example from your README.md @metehus

**Comment by metehus** [comment]
sorry im just kidding, you just need to remove this variable, thats just a information thing:
```
const Pornsearch = require('pornsearch');
const Searcher = new Pornsearch(args.slice().join(' '), 'redtube');
```
