### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by CitizenFiftyTwo** [LucasLeandro1204/Pornsearch#32]
Hello,

I am trying some researches but I always end up with 

`'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Do you know how to solve this issue ?

**Comment by LucasLeandro1204** [comment]
This package is not ment to be used in browser, but this is a cors issue, you have to proxy requests through a server
