### ISSUE TITLE
Change module loading

### ISSUE THREAD

**Issue by LucasLeandro1204** [LucasLeandro1204/Pornsearch#8]
Currently I'm doing this way:
https://github.com/LucasLeandro1204/Pornsearch/blob/master/src/Pornsearch.js#L78

But It's never gonna work in browser, so we have to require every module instead of searching for them.
It will be easy xd

**Comment by marcelorl** [comment]
Im taking this one.

**Comment by marcelorl** [comment]
https://github.com/LucasLeandro1204/Pornsearch/pull/10

**Comment by LucasLeandro1204** [comment]
@marcelorl You can close this pr now then recreate after October 1, because if I merge it now it will not count to promo, but thank you xd

**Comment by marcelorl** [comment]
really???

Actually, I dont care.

You can merge it if you want.

You may open other issues to add tests...what do you think? Then I add them after october 1st.

**Comment by LucasLeandro1204** [comment]
@marcelorl I was about to do that hahaha, ok so I will merge it now xd

**Comment by marcelorl** [comment]
awesome. thank you bro.
